#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  4 17:26:57 2020

@author: kong44
"""

# this doesn't work for George because this can only support 2 items in the value list
l = [[1,'A'],[1,"B"],[2,"c"]]
d = {}
for key, val in l: 
    d.setdefault(key,[]).append(val)
    
print(d)